"""Add drop_off, pickup_code, collected to Appointment

Revision ID: 0fb5fdfde93f
Revises: 5591040cd1fb
Create Date: 2025-06-29 17:39:03.706526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fb5fdfde93f'
down_revision = '5591040cd1fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drop_off', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('pickup_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('collected', sa.Boolean(), nullable=True))
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=False)
        batch_op.drop_column('collected')
        batch_op.drop_column('pickup_code')
        batch_op.drop_column('drop_off')

    # ### end Alembic commands ###
