"""add vet_id to clinical_history

Revision ID: 45d546f103f0
Revises: 0fb5fdfde93f
Create Date: 2025-07-02 21:13:39.359840

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '45d546f103f0'
down_revision = '0fb5fdfde93f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.alter_column('vet_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('clinical_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vet_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['vet_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinical_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('vet_id')

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.alter_column('vet_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
