"""add status to appointment

Revision ID: 5591040cd1fb
Revises: e293e2bd85a7
Create Date: 2025-06-28 18:06:00.278955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5591040cd1fb'
down_revision = 'e293e2bd85a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
