"""Fix appointment client_id foreign key

Revision ID: e293e2bd85a7
Revises: 1031b4f82d4e
Create Date: 2025-06-28 16:45:13.838041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e293e2bd85a7'
down_revision = '1031b4f82d4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('appointment_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'client', ['client_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('appointment_ibfk_1'), 'user', ['client_id'], ['id'])

    # ### end Alembic commands ###
